---
name: Publish Snapshot

on:
  push:
    branches:
      - main
      - 2.x

jobs:
  snapshot:
    name: Snapshot
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Build and Run Tests
        run: |
          ./gradlew publishPluginZipPublicationToZipStagingRepository

      - name: Extract Branch Name
        id: branch
        shell: bash
        run: echo "name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest-${{ steps.branch.outputs.name }}
          prerelease: true
          title: Development Build (${{ steps.branch.outputs.name }})
          files: |
            LICENSE.txt
            build/distributions/*